### ISSUE TITLE
Cannot run under mac os or linux.

### ISSUE THREAD

**Issue by aiddroid** [caoqianming/django-vue-admin#68]
```shell
 allen@MacBook  ~/dev/django-vue-admin/client   master ±  pnpm run dev

> vue-admin-template@4.2.1 dev /Users/allen/dev/django-vue-admin/client
> set NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve

 INFO  Starting development server...
 10% building 2/2 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:9528/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/allen/dev/django-vue-admin/client/public
ℹ ｢wds｣: 404s will fallback to /index.html
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/graceful-fs@4.2.11/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)
 10% building 2/5 modules 3 active ...r/client/index.js?http://localhost:9528node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:401:16)
    at handleParseError (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:449:10)
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:481:5
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/webpack@4.28.4/node_modules/webpack/lib/NormalModule.js:342:12
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/loader-runner@2.4.0/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/enhanced-resolve@4.5.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/graceful-fs@4.2.11/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

after run `export NODE_OPTIONS=--openssl-legacy-provider`, there's a new error on `npm run dev`:
```shell
Failed to compile.

./src/main.js
Module build failed (from ./node_modules/.pnpm/babel-loader@9.1.3_@babel+core@7.23.9_webpack@4.47.0/node_modules/babel-loader/lib/index.js):
TypeError: this.getOptions is not a function
    at Object.loader (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/babel-loader@9.1.3_@babel+core@7.23.9_webpack@4.47.0/node_modules/babel-loader/lib/index.js:44:28)
    at Object.<anonymous> (/Users/allen/dev/django-vue-admin/client/node_modules/.pnpm/babel-loader@9.1.3_@babel+core@7.23.9_webpack@4.47.0/node_modules/babel-loader/lib/index.js:39:12)
```

**Comment by caoqianming** [comment]
node18 ubuntu 
![image](https://github.com/caoqianming/django-vue-admin/assets/21101210/83bd65a8-ba8c-4e84-82e8-c99b801994c2)
export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve
npm run dev 测试OK

**Comment by aiddroid** [comment]
works fine with nodejs v18.0.0
